### ISSUE TITLE
Makefile: Shift linking arguments

### ISSUE THREAD

**Issue by YggdrasiI** [PDKK/freetypeGlesRpi#5]
Hello,

the linking for Non-RPi-systems requires an other argument order. Otherwise, it will not work with all compilers (in my case gcc4.8.1 on Ubuntu 14.04).
``
 @echo " Linking...";  $(CC) $^ -o $(TARGET) $(LIBS)
``

Regards Yggdrasil

**Comment by PDKK** [comment]
Interesting ... it works on Fedora 21 using gcc 4.9.2. Happy to make the change, but I need to check it on all builds first.
I have checked that it still works ok on Fedora, need to verify on Raspbian X and no X builds.

**Comment by PDKK** [comment]
OK, all tested so pushed. 
Regards
Paul
